export const REC_KEYS = {
  profile: (userId: number) => `rec:profile:${userId}`,
  personal: (userId: number) => `rec:personal:${userId}`,
  cobought: (productId: number) => `rec:cobought:${productId}`,
  similar: (productId: number) => `rec:similar:${productId}`,
  crosssell: (productId: number) => `rec:crosssell:${productId}`,
  segTrending: (locale: string, role: string) => `rec:seg:${locale}:${role}:trending`,
  segTrendingCat: (locale: string, role: string, catId: number) => `rec:seg:${locale}:${role}:trending:${catId}`,
  segNew: (locale: string, role: string) => `rec:seg:${locale}:${role}:new`,
  crosssellRules: 'rec:rules:crosssell',
  configWeights: 'rec:config:weights',
  configDecay: 'rec:config:decay',
  configToggles: 'rec:config:toggles',
  editorialPicks: 'rec:editorial:picks',
  feedbackImpressions: (date: string, algo: string) => `rec:feedback:${date}:${algo}:impressions`,
  feedbackClicks: (date: string, algo: string) => `rec:feedback:${date}:${algo}:clicks`,
  feedbackConversions: (date: string) => `rec:feedback:${date}:total:conversions`,
  metaLastRun: 'rec:meta:lastRun',
  metaLastDuration: 'rec:meta:lastDuration',
  metaProductCount: 'rec:meta:productCount',
  metaUserCount: 'rec:meta:userCount',
  lock: (jobName: string) => `rec:lock:${jobName}`,
  vendorBusinessTypes: (sellerId: number) => `rec:vendor:btype:${sellerId}`,
} as const;
