-- Add D (Dropship) to ProductType enum
-- This migration adds a new value 'D' to the ProductType enum for dropship products

-- Note: This is a complex migration that requires careful handling
-- The exact syntax may vary depending on your database system

-- For PostgreSQL:
-- ALTER TYPE "ProductType" ADD VALUE 'D';

-- For MySQL (if using enum):
-- ALTER TABLE Product MODIFY COLUMN productType ENUM('P', 'R', 'F', 'D') NOT NULL;

-- For SQLite (if using check constraints):
-- This would require recreating the table with the new enum values

-- Since this is a Prisma project, you should run:
-- npx prisma db push
-- or
-- npx prisma migrate dev --name add_dropship_product_type

-- The migration will be automatically generated by Prisma
