/**
 * @file create-category.dto.ts
 * @intent Defines the validation schema for category creation payloads using
 *         class-validator decorators.
 * @idea  Centralising input validation in a DTO class keeps the controller and
 *        service layers free of manual checks and enables automatic NestJS
 *        validation-pipe integration.
 * @usage Intended to be used as the @Body() type in CategoryController.create().
 *        Currently the active create route bypasses this DTO in favour of an
 *        untyped `any` payload (to support the `icon` field added in create2),
 *        so this DTO is only partially utilised.
 * @dataflow Incoming JSON body -> class-transformer instantiation ->
 *           class-validator decorators enforce constraints -> validated DTO
 *           passed to service.
 * @depends class-validator (IsString, IsEmail, MinLength, IsNumber, IsNotEmpty).
 * @notes  - IsEmail and MinLength are imported but never applied to any field;
 *           they are leftover from scaffolding and can safely be removed.
 *         - The `id` field has no validation decorators; it is typically
 *           auto-generated by the database and should not be supplied by
 *           the client on creation.
 *         - This DTO does not include an `icon` field, which is why the
 *           controller switched to `any` typing for the create endpoint.
 */
import { IsString, IsEmail, MinLength, IsNumber, IsNotEmpty } from 'class-validator';

export class CreateCategoryDto {
    /** @intent Database primary key placeholder (auto-generated; not client-supplied). */
    id: number;


    /**
     * @intent Human-readable label for the category.
     * @notes  Must be a non-empty string; validated by @IsNotEmpty + @IsString.
     */
    @IsNotEmpty()
    @IsString()
    name: string;

    /**
     * @intent References the parent category's id, establishing the tree hierarchy.
     * @notes  Must be a non-empty number.  For root-level categories the caller
     *         should supply the appropriate sentinel or null at the service layer.
     */
    @IsNotEmpty()
    @IsNumber()
    parentId: number;

    /**
     * @intent Identifies which menu this category belongs to (foreign key to the
     *         Menu / top-level category).
     * @notes  Must be a non-empty number.
     */
    @IsNotEmpty()
    @IsNumber()
    menuId: number;

    /**
     * @intent Classifies the category (e.g., product type, service type).
     * @notes  Must be a non-empty string.  Allowed values are enforced at the
     *         business-logic or database level, not in this DTO.
     */
    @IsNotEmpty()
    @IsString()
    type: string;
}
