/**
 * @file create-user.dto.ts — Data Transfer Object for User Registration
 *
 * @intent
 *   Validates the request body for POST /user/register. Ensures all required
 *   fields are present and correctly typed before the data reaches UserService.
 *
 * @idea
 *   Uses class-validator decorators for declarative validation. The global
 *   ValidationPipe (configured in main.ts with `whitelist: true`) strips
 *   unknown properties and validates the remaining fields against these rules.
 *
 * @usage
 *   - Used in UserController.register(@Body() createUserDto: CreateUserDto)
 *   - Consumed by UserService.create(createUserDto)
 *   - Frontend sends this payload from the registration form.
 *
 * @dataflow
 *   Frontend POST /user/register → ValidationPipe → CreateUserDto → UserService.create()
 *
 * @depends
 *   - class-validator (IsString, IsEmail, MinLength, IsOptional, IsEnum)
 *
 * @notes
 *   - TypeTrader enum is defined locally (not shared from Prisma schema). This
 *     includes MEMBER and ADMINMEMBER roles in addition to BUYER/FREELANCER/COMPANY.
 *   - `cc` represents the country calling code for the phone number (e.g., "+1").
 *   - `loginType` indicates the authentication method (e.g., "email", "google").
 *   - `password` requires minimum 8 characters via @MinLength(8).
 *   - `id` is optional and typically not sent by the client (auto-generated by DB).
 *   - `dateOfBirth`, `gender`, and `profilePicture` are optional fields that
 *     can be provided during registration (e.g., from Google OAuth profile data).
 */

import {
  IsString,
  IsEmail,
  MinLength,
  IsOptional,
  IsEnum,
} from 'class-validator';

/**
 * TypeTrader — Enum of allowed trade roles for user registration.
 * Maps to the Prisma TradeRole enum in the database schema.
 * - BUYER: Standard buyer account.
 * - FREELANCER: Individual seller/service provider.
 * - COMPANY: Business/organization account.
 * - MEMBER: Team member (sub-user under a seller/company).
 * - ADMINMEMBER: Admin team member with elevated permissions.
 */
enum TypeTrader {
  BUYER = 'BUYER',
  FREELANCER = 'FREELANCER',
  COMPANY = 'COMPANY',
  MEMBER = 'MEMBER',
  ADMINMEMBER = 'ADMINMEMBER',
}

export class CreateUserDto {
  id?: number;                  // Optional — auto-generated by DB; only used for internal references

  @IsString()
  firstName: string;            // User's first name

  @IsString()
  lastName: string;             // User's last name

  @IsEmail()
  email: string;                // User's email — used as the login identifier

  @IsString()
  @MinLength(8)
  password: string;             // Password (plaintext) — hashed by UserService before storing

  @IsString()
  cc: string;                   // Country calling code (e.g., "+966", "+1")

  @IsString()
  phoneNumber: string;          // Phone number without country code

  @IsEnum(TypeTrader)
  tradeRole: TypeTrader;        // The user's role on the platform

  @IsString()
  loginType: string;            // Authentication method: "email" | "google" | etc.

  @IsOptional()
  @IsString()
  dateOfBirth?: string;         // Optional date of birth (string format)

  @IsOptional()
  @IsString()
  gender?: string;              // Optional gender

  @IsOptional()
  @IsString()
  profilePicture?: string;      // Optional profile picture URL (e.g., from Google OAuth)
}
